### ISSUE TITLE
The discord link is fucked.

### ISSUE THREAD

**Issue by Technerder** [impulse-cl/impulse#23]
The discord link in the README.md file of the repository and the discord #share-your-projects channel in the CodeVision discord are broken.

**Comment by Shad0wCore** [comment]
![image](https://user-images.githubusercontent.com/17110757/44073239-26ca0614-9f93-11e8-845e-d0be53a344ca.png)

Thank you! Going to change the invite link right away.
I deleted the #welcome channel earlier which might have made the link invalid.

Here's the new one: https://discord.gg/F8h54jX

**Comment by MiniDigger** [comment]
I also updated the link on codevision
